---
- name: Yaml Playbook to fetch the App module version deployed on each server
  hosts: 127.0.0.1
  become: yes
  gather_facts: True
  tasks:
   - name: execute the check.yaml
     shell: ansible-playbook hosts.yaml -k -e "DeployHost={{ item.ip }}"  -e "EnvName={{ item.name }}" 
     with_items:
       - { name: dit1, ip: 192.168.77.21 }
       - { name: dit2, ip: 192.168.77.21 }
         #         - { name: sit1, ip: 192.168.77.21 }
         #       - { name: sit2, ip: 192.168.77.21 }
     register: Mercury
   - debug:
       msg: "{{ Mercury }}"
   - name: execute report_final.sh script to generate final .csv file.
     shell: ./report_final.sh 
     delegate_to: 127.0.0.1
     register: Final_CSV
    
   - debug:
       msg: "{{ Final_CSV }}"

...

