
---
- name: Yaml Playbook to fetch the App module version deployed on each server
  hosts: 127.0.0.1
  gather_facts: True
  tasks:
   - name: execute the check.yaml
     shell: ansible-playbook hosts.yaml -k -e "DeployHost={{ item.ip }}"  -e "EnvName={{ item.name }}"
     with_items:
       - { name: dit1, ip: 192.168.77.21 }
       - { name: dit2, ip: 192.168.77.21 }
         #         - { name: sit1, ip: 192.168.77.21 }
         #       - { name: sit2, ip: 192.168.77.21 }
     register: Mercury
   - debug:
       msg: "{{ Mercury }}"
   - name: execute report_final.sh script to generate final .csv file.
     shell: ./report_final.sh "{{ dest_node }}" "{{ src_node }}"
     delegate_to: 127.0.0.1
     register: Final_CSV

   - debug:
       msg: "{{ Final_CSV }}"

   - name: base url setting
     set_fact:
        baseurl: "http://code-artifacts.bankofamerica.com:18081/artifactory/libs-release-local-maven/com/baml/crdtctr/"


   - name: calling the ansible playbook to make the artifactory and fetch that
     shell: |
            mod=$(echo {{ item }} |cut -d, -f1)
            ver=$(echo {{ item }} |cut -d, -f2)
            mod1=$(echo $mod|tr '-' '_')
            if [[ "api-gateway" == "$mod" ]]; then
                echo "Set module url api-gateway"
                module_art=("{{ baseurl }}/$mod1/$mod/$mod-$ver.zip")
            elif [[ "api-domain" == "$mod" ]]; then
                echo "Set module url api-domain"
                module_art=("{{ baseurl }}/$mod1/$mod/$mod-$ver.zip")
            elif [[ "api-sharedlib" == "$mod" ]]; then
                echo "Set module url api-sharedlib"
                module_art=("{{ baseurl }}/$mod1/$mod/$mod-$ver.zip")
            elif [[ "moudle1" == "$mod" ]]; then
                echo "Set module url api-raml"
                module_art=("{{ baseurl }}/$mod1/$mod/$mod-$ver.zip")
            elif [[ "moudle2" == "$mod" ]]; then
                echo "Set module url module2"
                module_art=("{{ baseurl }}/$mod1/$mod/$mod-$ver.zip")
            else
                echo "wrong set of module name, exiting"
                exit 127

            fi
            echo "$module_art"

            if [[ {{ dest_node }} == "dit1" ]];then
                DeployHost=192.168.77.21
            elif [[ {{ dest_node }} == "dit2" ]]; then
                DeployHost=192.168.77.21
            elif [[ {{ dest_node }} == "dit3" ]]; then
                DeployHost=192.168.77.21
            elif [[ {{ dest_node }} == "sit1" ]]; then
                DeployHost=192.168.77.21
            elif [[ {{ dest_node }} == "sit2" ]]; then
                DeployHost=192.168.77.21
            elif [[ {{ dest_node }} == "sit3" ]]; then
                DeployHost=192.168.77.21
            elif [[ {{ dest_node }} == "uat1" ]]; then
                DeployHost=192.168.77.21
            elif [[ {{ dest_node }} == "uat2" ]]; then
                DeployHost=192.168.77.21
            elif [[ {{ dest_node }} == "t2" ]]; then
                DeployHost=192.168.77.21
            elif [[ {{ dest_node }} == "dit4" ]]; then
                DeployHost=192.168.77.21
            else
                echo "host not defined hence exiting"
                exit 128
            fi

            echo "$DeployHost"
            module_art1="http://stash.compciv.org/ssa_baby_names/names.zip"
            echo "$module_art1"
            echo 'ansible-playbook hosts2.yaml -e "DeployHost='$DeployHost'" -e "Module='$module_art1'" -e "dest_node={{ dest_node }}" -e "mod1='$mod'"'
            ansible-playbook hosts2.yaml -e "DeployHost=$DeployHost" -e "Module=$module_art1" -e "dest_node={{ dest_node }}" -e "mod1=$mod"


     args:
       executable: /bin/bash  

     with_lines:
       - "cat $HOME/test/report/final/report_filter.csv "
     register: lookit


   - debug:
       msg: "{{ lookit }}"


