---
- name: Yaml Playbook to fetch the App module version deployed on each server
  hosts: 127.0.0.1
  gather_facts: True
  tasks:
   - name: execute the check.yaml
     shell: ansible-playbook hosts.yaml -k -e "DeployHost={{ item.ip }}"  -e "EnvName={{ item.name }}" 
     with_items:
       - { name: dit1, ip: 192.168.77.21 }
       - { name: dit2, ip: 192.168.77.21 }
         #         - { name: sit1, ip: 192.168.77.21 }
         #       - { name: sit2, ip: 192.168.77.21 }
     register: Mercury
   - debug:
       msg: "{{ Mercury }}"
   - name: execute report_final.sh script to generate final .csv file.
     shell: ./report_final.sh 
     delegate_to: 127.0.0.1
     register: Final_CSV
    
   - debug:
       msg: "{{ Final_CSV }}"

   - name: base url setting
     set_fact:
        baseurl: "http://code-artifacts.bankofamerica.com:18081/artifactory/libs-release-local-maven/com/baml/crdtctr/"
        dit1: 171.x.x.x
        dit2: 172.x.x.x
        sit1: 173.x.x.x
        sit2: 174.x.x.x
        dit1_home: /ciohosting/cce2e/dit1/cce2e-382-mule/apps/
        dit2_home: /ciohosting/cce2e/dit2/cce2e-382-mule/apps/
        sit1_home: /ciohosting/cce2e/sit1/cce2e-382-mule/apps/
        sit2_home: /ciohosting/cce2e/sit2/cce2e-382-mule/apps/

   - name: here we have to get the logic for the Csv comparision
     shell: echo "yes"
     
   - name: Execute the script to get the module name that need to be deployed.
     shell: ./1 mod
     register: mod
    
   - name: Execute the script to get the module version that need to be deployed.
     shell: ./1 ver
     register: ver
    
   - debug:
      msg: "{{ ver }} {{ mod }}"

   - name: calling the ansible playbook to make the artifactory and fetch that 
     shell: ansible-playbook sample.yaml -e "{{ mod_name=item.mod }}" -e "{{ version=item.ver }}"
     with_items:
       - { ver: "{{ ver.stdout_lines }}", mod: "{{ mod.stdout_lines }}" }


...
